runtime: nodejs
env: flex
service: default

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

env_variables:
  NODE_ENV: "production"

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: build/static
- url: /(.*\.(json|ico|js))$
  static_files: build/\1
  upload: build/.*\.(json|ico|js)$
- url: .*
  static_files: build/index.html
  upload: build/index.html