FROM node:14 as frontend-build
WORKDIR /yaya/client
COPY yaya/client/package*.json ./
RUN npm install
COPY yaya/client .
RUN npm run build

FROM nginx:1.17.1-alpine
COPY --from=frontend-build /yaya/client/build /usr/share/nginx/html


