runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

env_variables:
  NODE_ENV: "production"

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

network: 
  forwarded_ports:
    - 3001/tcp