# Stage 1: Python environment for scripts
FROM python:3.9 AS scripts-env
WORKDIR /scripts
COPY scripts/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY scripts/ ./

# Stage 2: Node environment for server
FROM node:14
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Copy python scripts from the first stage
COPY --from=scripts-env /scripts ./scripts

# Expose port for server
EXPOSE 8080

# Start server
CMD ["node", "app.js"]
